### ISSUE TITLE
HMRC-OVERSEAS-TRADE-STATISTICS

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#10]

**Comment by JasonHowell** [comment]
@ajtucker Is this part of Trade?   If not, should this be closed?

**Comment by ajtucker** [comment]
This one is listed in Airtable, but I'm not sure whether it is subsumed by the other HMRC OTS datasets or needs to be kept as a separate placeholder. @RobThomlinson ?

**Comment by JasonHowell** [comment]
@ajtucker   Rob's comments from Slack "I Have Overseas Trade Statistics (CN8)- HMRC (published on PMD) and OVERSEAS TRADE STATISTICS - HMRC on airtable, they are the same thing.  I don't have anything anywhere listed as HMRC OTS, but OTS is a "normal" abbreviation for Overseas Trade Statistics, so best guess is that it is the same thing"

**Comment by JasonHowell** [comment]
This is a duplicate of Overseas Trade Statistics (CN8) #14, hence closing issue.
