### ISSUE TITLE
columns.csv to info.json

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#103]
For all the trade dataset that targeted PMD3, the transformation pipeline would end up uploading the Tidy CSV file to PMD3 along with a family-wide definition of how column names map to dimensions, attributes and measures: `columns.csv`. PMD3 would then run its own pipeline using `table2qb` to convert the Tidy CSV to an RDF Data Cube, using this configuration file.

This time around we are declaring these column name to dimension mappings in individual `info.json` files along with the each dataset transformation pipeline.

By default, if no mapping is declared for a column, a "local" (to the dataset) dimension is coined and used and will point to a "local" codelist.

Given that we already have the necessary set of dimensions and codelists -- we're aiming to make things look the same as on trade.gss-data.org.uk, we should re-use the information in this `columns.csv` file, putting it into these individual `info.json` files.

The measure dimensions are a little more complex, so we can do this as a separate task.

This could be done by hand or scripted, whichever is easier/faster.

- [ ] Work through an example.
- [ ] Repeat for each dataset.

**Comment by JasonHowell** [comment]
@ajtucker Is this still an issue as referenced to PmDv3 and now we are on Beta(PmDv4)?

**Comment by ajtucker** [comment]
I believe this has effectively been done, just with much more manual effort than I'd imagined. Closing.
