### ISSUE TITLE
ONS-UK-Ecconomic-Accounts-balance-of-payments-current-account

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#11]

**Comment by MartynBSpooner** [comment]
Cannot upload to PMD3 - needs further investigation - returns Datacube NULL.

**Comment by ajtucker** [comment]
The 'null' response seems to come from the additional processing done on PMD after `table2qb`, where labels are created for `sdmx:refPeriod` values.

The `Period` column needs to be updated to use the template for "government" intervals given by https://github.com/epimorphics/IntervalServer/blob/master/interval-uris.md#user-content-modern-government-business-intervals, e.g. `government-year/1997-1998`.

**Comment by LPerryman** [comment]
I have removed the CDIDs for now just to get the data on PMD4, can easily be put back when needed. 
Currently each dataset has the same Title, Comment and Description but obviously they need to be different. 
Not sure how to do this in the cubes class so i have added what I want each one to be within each section using:
scraper.dataset.title
scraper.dataset.comment
scraper.dataset.description
Could someone fix this so the correct metadata is output please?

**Comment by osamede20** [comment]
Script revised to output different title, comment and description for each dataset respectively.
Measure type changed to bop-capital-account for the Capital Account dataset.

**Comment by LPerryman** [comment]
Morning @osamede20 Looks like the title, comment and description are still the same for all output trig files! could you have another look please?

**Comment by osamede20** [comment]
Good day @LPerryman,
Thanks for the observation. 
I have revised the main.py script to output trig data with different title, comment and description for each respective dataset. Please let me know if I have missed anything.

**Comment by LPerryman** [comment]
Thanks @osamede20

**Comment by Shannon95** [comment]
Multiple outputs ready for review here : 
[UK Economic Accounts: balance of payments - Capital Account](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-capital-account-catalog-entry&filters-drawer=open)

[UK Economic Accounts: balance of payments - Current Account - Primary Income](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-primary-income-catalog-entry&filters-drawer=open)

[UK Economic Accounts: balance of payments - Current Account - Secondary Income](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-secondary-income-catalog-entry&filters-drawer=open)

[UK Economic Accounts: balance of payments - Current Account - Summary of balance of payments](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-summary-of-balance-of-payments-catalog-entry)

[UK Economic Accounts: balance of payments - Current Account - Trade in goods and services](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-trade-in-goods-and-services-catalog-entry&filters-drawer=open)

[UK Economic Accounts: balance of payments - Current Account - Transactions with non-EU countries](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-transactions-with-non-eu-countries-catalog-entry)

[UK Economic Accounts: balance of payments - Current Account - Transactions with the EU and EMU](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-transactions-with-the-eu-and-emu-catalog-entry&filters-drawer=open)

**Comment by JasonHowell** [comment]
This has been reviewed by the publisher and some observations given on sort order but nothing needs to be actioned.
