### ISSUE TITLE
ONS-UK-Trade-in-goods-CPA-08

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#15]

**Comment by Shannon95** [comment]
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context?
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by Shannon95** [comment]
Now available on PMDv4, removing label and checking review via PMDv4 side

**Comment by Shannon95** [comment]
CDID's now added into transformation and passing, updated version is now on PMDv3. I have created an issue with Swirl to update PMDv4 with the latest version. 
https://github.com/Swirrl/ons-data-export/issues/26

**Comment by JasonHowell** [comment]
Not updated to latest version on PMDv4.  Modified date is still 21st should be 29th April.

**Comment by JasonHowell** [comment]
BA's have reviewed and good to go.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by osamede20** [comment]
The transform scraper was re-worked and a pull request opened. The PR was reviewed and minor changes requested (removing legacy code and add TransformTrace) . Upon making the changes, running the code and doing a double check on the CSV output (before pushing the commit to GitHub), it was discovered that the scraper is not working correcting.

The transform scraper is not picking up the correct dimension attributes - 'Product Category' and 'Product' for most of the dimension 'Product Department'. This can be seen from record 1417 in the CSV output data. This has to do with the HDim construct - accurately defining the relationship between the dimensions and the observations.

**Comment by osamede20** [comment]
Transform of dataset is unblocked.
Scraper is re-written to produce accurate CSV output data.

**Comment by rossbowen** [comment]
CDIDs treated as a dimension for now while we wait for this issue to become unblocked.

**Comment by Shannon95** [comment]
Looking into this dataset I have noticed the following and need some advice on how to proceed; 
- Some CDID's have blank values due to the entry having a cross over of product codes like **10.2-3**, which don't exist (I am assuming this represents 10.2 and 10.3 as they do exist and have associated CDID codes )
![image](https://user-images.githubusercontent.com/55798687/107621246-db274e80-6c4d-11eb-9b9f-cbbaf090eb4c.png)

- Though I don't see why this dataset is blocked by CDID's as all the information is held within the spreadsheet so can be pulled out during transformation? should the CDID then be treated as an attribute? 

not sure if this is something we should go back to the publisher on.

**Comment by rossbowen** [comment]
@Shannon95 I suppose if there is no additional data external to the spreadsheet then there's nothing more to do here - I think the right approach would be as you say to treat CDID as an attribute.

```
"attribute": "http://gss-data.org.uk/def/trade/property/attribute/cdid",
"value": "http://gss-data.org.uk/def/concept/trade/cdid/{cdid}"
```

**Comment by robons** [comment]
@Shannon95 there's a problem with the build here - https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-Trade-in-goods-CPA-08/80/console

I'll throw this one back at you guys to look at fixing. I believe @mikeAdamss is looking at some kind of similar problem with https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-Quarterly-country-and-regional-GDP/22/console

**Comment by mikeAdamss** [comment]
@Shannon95 - i think its because we're using a generator comrehension, this:

`tabs = (t for t in distribution.as_databaker())`

these had a tweak in python 3.8, i suspect its failing and our dodgy stack is swallowing the error.

if you switch to a classic `tabs = distribution.as_databaker()` I suspect it'll work fine.

**Comment by Shannon95** [comment]
working with the newest gssutils build (v0.12.4). Now failing at  _Run SPARQL Tests on Draftset_

**Comment by robons** [comment]
I've created a spec.md in the https://github.com/GSS-Cogs/family-trade/commit/e162991226ee290c54e80261ad68fb9fa63dae47 for this dataset. It's in a really convoluted format. Hopefully these simpler changes should put it back in a better place.

Passing back to DEs to work on. Perhaps you want to pick it up @osamede20 ?

**Comment by osamede20** [comment]
@robons Yes, I will pick this up.
Thanks for the spec.

**Comment by robons** [comment]
@Tracey-B this is now up on PMD4 if you could please review. 

https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-goods-cpa-08-catalog-entry&filters-drawer=open

**Comment by Tracey-B** [comment]
@robons @rossbowen BA checks completed, the Datset looks reasonable subject to the follwing comments:

- I am unable to tell if this seasonally adjusted or not from either the title or obsrvation.  Additionally some of the datasets have an seasonally adjusted field e.g. Trade in goods: all countries, seasonally adjusted.   
-  Unable to filter by period.
-

**Comment by JasonHowell** [comment]
This can be closed as published on the BETA env.
