### ISSUE TITLE
Some datasets have very long values for rdfs:comment

### ISSUE THREAD

**Issue by BillSwirrl** [GSS-Cogs/family-trade#167]
For example https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry

In this example, it looks like perhaps the values for rdfs:comment and the dct:description are the wrong way round.

As well as being very long, the value for the comment currently has markdown in it, which the datasets list in the catalogue does not attempt to render, so it looks a bit broken  (though the description field in the About tab can render markdown)

**Comment by JasonHowell** [comment]
The datasets which had these issues have been updated and look fine on the BETA site.

Hence closing this issue.
