### ISSUE TITLE
ONS-UK-trade-in-services

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#17]
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-UK-trade-in-services

**Comment by JasonHowell** [comment]
BA QA Feedback  - Tracey B

BA Quality Assurance High Level Checks 
Dataset:  UK total trade: all countries, non-seasonally adjusted
Completed by: Tracey Burgess
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
10/03/2020
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
26/03/2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No*
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*Unable to apply filters to Reference Period & Product
*Measure Type should not be included in the list of filterable dimensions and is this required as well as Unit of measure and GBP Total?

Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

See above re Measure type, unit of measure and GBP total

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by ajtucker** [comment]
DIT have also reviewed this dataset:

> It looks like 2016-Q1 is missing from all of the data pulled in from https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/datasets/uktradeinservicesservicetypebypartnercountrynonseasonallyadjusted. The spreadsheet itself looks to contain data for this quarter - would it be possible to get this added back in?

> It looks like there is 2016-Q1 data for all the countries which are added from https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-UK-trade-in-services/Trade%20in%20Services%20by%20Country.py (the countries where there's only total trade for services data).

@RedWalters, could you take a butchers?

**Comment by JasonHowell** [comment]
BA have confirmed this is good to go.

**Comment by RedWalters** [comment]
2016-Q1 missing data fixed. Current issue on pipeline is related to ONS Partner Geography - missing 'PB' codes in sdmx-bop/cl_area.

**Comment by JasonHowell** [comment]
@RedWalters is this now fixed?

**Comment by JasonHowell** [comment]
Caught up with J "I believe so, moving the dimension to use CORD geography rather than cl_area should have remedied that"  Hence closing issue.

**Comment by JasonHowell** [comment]
Closing down as old comments.  Published to the Beta site and looks fine. 

https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-catalog-entry
