### ISSUE TITLE
HMRC-trade-in-goods-by-business-characteristics failed

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#175]
Jenkins job result: FAILURE
Stage: Tidy CSV
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC-trade-in-goods-by-business-characteristics/203/)

Blocks #8

**Comment by Shannon95** [comment]
Blocked by  GSS-Cogs/gss-utils#253

**Comment by JasonHowell** [comment]
GSS-Cogs/gss-utils#253 - this has now been resolved.   The transform needs to be updated.
