### ISSUE TITLE
ONS-UK-trade-in-services-by-industry-country-and-service-type-exports failed

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#184]
Jenkins job result: FAILURE
Stage: Validate CSV
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/88/)

Blocks #80

**Comment by JasonHowell** [comment]
Pipeline automated failure ticket - Schema for mixed code lists. 

See Schema for mixed codelists for more details.  Once approach has been resolved this pipeline needs to be updated.

**Comment by ajtucker** [comment]
I think this is an old duplicate of #228 and can be closed.
