### ISSUE TITLE
ONS-UK-Trade-in-goods-CPA-08 - QA Feedback

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#188]
As per QA feedback meeting on 14/06/2021 from Sarah Whiting two actions to be resolved:

AP01 – see how to highlight the importance of residual seasonal adjustment.
AP02 – to add “seasonal adjusted” to the tittle description.

**Comment by LPerryman** [comment]
Have changed title to
UK Trade in goods by Classification of Product by Activity, time series dataset, Quarterly and Annual
and also added comment and description.

Have published but Periods are now showing as URIs! I think some missing period script needs to be run. i have run ref_periods pipeline but this did not fix the issue

**Comment by JasonHowell** [comment]
@rossbowen    Please could you confirm the two QA observations have been fixed and that the update has been applied to the Beta site.  

If the above is done this can then be closed.

**Comment by JasonHowell** [comment]
Held a QA session with Sarah Whiting and Marc John.  There are two versions of this publication on Beta.
Although I can only find one now:

https://beta.gss-data.org.uk/datasets?filter-state=%5B%22%5E+%22%2C%22~%3Astate%2Ffilter-term%22%2C%2208%22%5D

**Comment by Shannon95** [comment]
Updates made in line with QA feedbacks completed. 
[Beta](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-goods-cpa-08-catalog-entry)

[Staging](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-goods-cpa-08-catalog-entry&apply-filters=true)

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/02/22 and all good - can be closed
