### ISSUE TITLE
MRETS rework

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#19]
There are some problems with the way we were transforming this dataset, not least because the dimensions and codelists were being drawn from some manual searching of the internal (to ONS) CSDB.

Moving to using the "structured database" version of the distribution means that we can better extract the information we need directly from the publication.

- [x] Start from the CSDB structured text version
- [x] Parse label of the slice to figure out dimensions and codes
- [x] Dissect into multiple cubes as necessary
- [ ] Output labels for codelists and slices
- [ ] Output schema and dataset metadata for each separate cube

**Comment by ajtucker** [comment]
Blocks #5

**Comment by JasonHowell** [comment]
@ajtucker Is this done now?  Should it be moved to the Transformation Pipeline project?

**Comment by ajtucker** [comment]
I believe @mikeAdamss finished this off.

**Comment by mikeAdamss** [comment]
@JasonHowell - yeah this was done on a different card. Closing.
