### ISSUE TITLE
ONS-UK-trade-in-services-by-industry-country-and-service-type-exports failed

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#191]
Jenkins job result: FAILURE
Stage: Run SPARQL Tests on Draftset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/5/)

Blocks #80

**Comment by Shannon95** [comment]
Passing on both Master and Beta pipeline. Closing issue.
https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/
https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/
