### ISSUE TITLE
ONS-Regional-gross-domestic-product-city-regions failed

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#192]
Jenkins job result: FAILURE
Stage: Data Cube
[View full output](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Regional-gross-domestic-product-city-regions/3/)

Blocks #79

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Run SPARQL Tests on Draftset
[View full output](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Regional-gross-domestic-product-city-regions/4/)

Blocks #79

**Comment by LPerryman** [comment]
Have fixed this, fingers crossed
Lots of superscripts and notes being dragged from the spreadsheet
Have removed these and added some stuff to the gdp-estimate codelist
Have switched Area Name for Geography Code and removed rows that do not have any codes to make this dataset consistent with all the others and changed info.json to reflect this.
