### ISSUE TITLE
ONS-UK-Total-trade failed (on beta)

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#194]
Jenkins job result: FAILURE
Stage: Validate CSV
[View full output](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-Total-trade/9/)

Blocks #6

**Comment by JasonHowell** [comment]
This needs to be investigated and fixed.
