### ISSUE TITLE
Duplicates related to below threshold traders T2 and T3 on spreadsheet

### ISSUE THREAD

**Issue by Grace-W** [GSS-Cogs/family-trade#20]
Leigh and I were looking at the original spreadsheet and after discussion spotted that tab/table 3 had a duplicate for below threshold traders - the statistical value was listed as N/A. This information is counted in the statistical count on T2.

Leigh and I think that T3 needs to be removed.

**Comment by ajtucker** [comment]
@Grace-W , @LPerryman , @VTula2000 , is this still an issue, and is it related to #12 or #16 ?

**Comment by VTula2000** [comment]
Its fixed in RTS small area repository no more issue!
