### ISSUE TITLE
Publish on success in staging

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#230]
For the staging pipelines, once a draft dataset has passed all the validations and integrity constraints, we should publish the draftset.

We can also consider uploading the data to beta and submitting it for review.

Currently, adding the following to the `info.json` file will automatically publish the draft once all the tests have passed:

```
    "load": {
        "publish": true
    }
```

The following datasets already have this set:
* HMRC-overseas-trade-statistics
* HMRC-regional-trade-statistics
* ONS-Exports-of-services-by-country-by-modes-of-supply
* ONS-UK-trade-in-services-by-industry-country-and-service-type-exports

**Comment by JasonHowell** [comment]
@shannon95 - to write-up the process of using:

"load": {
        "publish": true
    }

to the Engineering community i.e. local working instruction. 

Est.  =  1

**Comment by Shannon95** [comment]
Closing Issue as this is now a known thing to do once the pipeline is passing.
