### ISSUE TITLE
QA - UK trade in goods by business characteristics 2019

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#240]
Feedback from the QA review with James and Nadeem:

-	Trade value should display “£”
-	Headers have URI’s references – Business-count, Employee-count
-	Both Business count and Employee count have .0 is this required.
-	UI – should columns be right aligned.

**Comment by santhosh-thangavel** [comment]
There is a latest Publication on 24 November 2021
https://www.gov.uk/government/collections/uk-trade-in-goods-statistics-by-business-characteristics#history

**Comment by Shannon95** [comment]
Updates that can be integrated have been completed in line with QA feedback. 
[Beta](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-trade-in-goods-by-business-characteristics-catalog-entry) 
[Staging](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-trade-in-goods-by-business-characteristics-catalog-entry&apply-filters=false) 

**Trade value should display “£”**
The unit of measure is in GBP.

**Headers have URI’s references – Business-count, Employee-count**
Labels now appear and not the URI for both Business Count and Employee Count. 

**Both Business count and Employee count have .0 is this required.**
.0 was not required and has been removed.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/02/22 and all good - can be closed
