### ISSUE TITLE
ONS-REUK-Service

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#25]

**Comment by LPerryman** [comment]
- [ ] Does the dataset show up or is there an error? Shows
- [ ] Is it in the list of datasets from the main page? 
- [ ] Is there descriptive metadata on the search page? 
- [ ] Does transformed info match the original? 
- [ ] Does the tidydata download show all the data? 
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide 
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work? 
- [ ] What needs further investigation or context? 
- [ ] Any duplications? 
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by IeuanMan** [comment]
@david-hull 

https://docs.google.com/document/d/1oeyK1uUl5FtP7x3rM_1lYjPRFheghh1bJdgjSKoSJeM/edit

BA Quality Assurance High Level Checks 
Dataset: Regionalised estimates of UK service exports
Done by: David Hull
Date: 6-4-20
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes but no overview
Does transformed info seem to match the original?
Yes
Contents Modified Date
2020-03-16
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
2 Apr 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No
Does the structure look sensible?
Yes

Overview
General comments on the dataset

2011 to 2016 is the latest release on the website landing page.
Data structure does look sensible but there is no real filtering and metadata could be more robust, in my opinion.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Metadata is available but there is no overview description in the “about” page.
Metadata is present in airtable.
No link available to the original website landing page.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

No real filtering available,only filter is on “flow” but there is only one option as all flow is export. Should be filtering on the other dimensions.
Looks odd to me to have a “GBP Total” column of it’s own with “GBP total” the main (if not only) entry in the “measure type”.
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent and looks sensible except for that noted above.

**Comment by JasonHowell** [comment]
BA confirmed this is good to go in its current state.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by osamede20** [comment]
Rework done on script 
Cube class added
Trace annotation added
Legacy code replaced

**Comment by rossbowen** [comment]
@Tracey-B For review at the following link:

https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-reuk-service-catalog-entry

**Comment by Tracey-B** [comment]
BA comments as discussed with @rossbowen:

- There is no tech spec for this dataset, therefore unable to determine if decisions have been made with some of the comments below and why.
- Unable to filter by most of the dimensions, additionally when opening the filter for ONS Functional Category, there are no categories displayed, the drop down box defaults to nested view,however when selecting flat view the categories become visible and can be filtered.
- Uris are present under reference area when all Nuts areas included.
- Measure type GBP Million only do we need to include %.
- Are the dimensions correct.  Reference area or Nuts1?  ONS Functional Category or Service?
