### ISSUE TITLE
QA - Trade ONS-UK-trade-in-services-by-business-characteristics

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#270]
There are a couple of URI's in the columns:

https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-trade-in-goods-by-business-characteristics-catalog-entry

This still needs a review by the publisher.

**Comment by RedWalters** [comment]
Staging - [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-business-characteristics-catalog-entry&order-by-component=http%253A%252F%252Fgss-data.org.uk%252Fdef%252Fmeasure%252Fcount&order-direction=DESC)

Beta - [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-business-characteristics-catalog-entry&order-by-component=http%253A%252F%252Fgss-data.org.uk%252Fdef%252Fmeasure%252Fvalue-of-trade&order-direction=DESC)

All URIs found in columns has been rectified. 
Data has also been updated.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/02/22 and all good - can be closed
