### ISSUE TITLE
QA - RTS

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#273]
Feedback from Maxim Mastrangelo  (maxim.mastrangelo@hmrc.gov.uk):

RTS 
-	Region is a numeric code rather than the alpha. e.g. it says W92000004 rather than Wales etc.
-	Seems to only have Q1 2021 is this intentional as it is just testing? Also, it appears you cannot filter on period, probably for this reason that there’s only 1 quarter of data available?
-	SITC4 column header should be renamed to ‘SITC’ maybe. RTS only goes to SITC 2 detail but has SITC 1 and 2 breakdowns.
-	SITC descriptions could include the numeric code alongside the alpha description. E.g. rather than just saying ‘Beverages’ it could say ’11 Beverages’ or have ‘11’ in an adjacent column.
-	Description can be found on the following page under ‘details’: https://www.gov.uk/government/statistics/uk-regional-trade-in-goods-statistics-first-quarter-2021

Generally across:
Some observations across the 3 different releases:
-	Is it possible to have Stat value and business count on the same line or does it need to be separate?
-	Could include comma separation on numbers if easy to apply
-	From 2021 all RTS releases will now report on ITL rather than NUTS as is the case in ONS I believe. This doesn’t affect RTS main quarterly release as we name it ‘Region’, but will lead to a change on the smaller geographical area release.

**Comment by Shannon95** [comment]
Duplicate to issue #238 therefore closing.
