### ISSUE TITLE
QA - Trade - International trade in services

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#278]
Held QA meeting with Elliott, Tyler <Tyler.Elliott@ons.gov.uk>  22/10/2021.  

Observation column has URI's listed not text.

**Comment by Shannon95** [comment]
The observation column no longer has URI's, is now valid text. Please see links below :
[
beta](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry)
[staging ](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry)

needs reviewed / approved before issue can be closed.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/01/22 and all good - can be closed
