### ISSUE TITLE
Footnotes in Energy Consumption Source codelist

### ISSUE THREAD

**Issue by Robsteranium** [GSS-Cogs/family-trade#279]
The [Energy Consumption Source codelist](https://staging.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Fclimate-change%2Fons-energy-use-total%23scheme%2Fenergy-consumption-source) has codes with labels like "Direct1 use of energy from fossil fuels" and "Reallocated1 use of energy". I guess these are keys to footnotes. The numbers should be stripped out of the labels/ URIs. It'd be nice if the contents of the footnote was included in the code description, perhaps using `rdfs:comment`...

**Comment by Shannon95** [comment]
Closing as raised in Trade repo belongs in Climate. Speak to Jason to raise.

**Comment by Robsteranium** [comment]
Ah sorry Shannon - too many tabs open!
