### ISSUE TITLE
ONS-REUK-Service

### ISSUE THREAD

**Issue by RedWalters** [GSS-Cogs/family-trade#319]
Uplifting ONS-REUK-Service to CSVCubed.

Currently working on 'csvcubed' branch.

**Comment by Shannon95** [comment]
Closing as has been uplifted to csvCubed and available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Ftrade%2Fons-reuk-service%2Fregionalised-estimates-of-uk-service-exports.csv%23catalog-entry)
Note link not available on beta atm as cannot run but will be once given the go ahead.
