### ISSUE TITLE
Annual Business Survey exporters and importers (ABS)

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/family-trade#32]

**Comment by mikeAdamss** [comment]
Fix of an older pipeline, just updating to newer coding conventions/style of pipeline. The data itself should be the same as it was previously.

**Comment by ajtucker** [comment]
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context?
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by VTula2000** [comment]
Review Comments
Observation with `Total` are missing in Final tidy data
Column heading need to be fixed with units as those units not covered in unit and measure type of final data, eg:  Turnover to be `Turnover in GBP`, Age of Business to be 'Age of Business in years',  Employment to be `Number of Employee` (or Employment Numerical labels need string definition)

**Comment by JasonHowell** [comment]
BA QA Feedback - Tracey B
BA Quality Assurance High Level Checks 
Dataset: Annual Business Survey exporters and importers
Completed by: Tracey Burgess
Date:
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
14/03/2020
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
31/03/2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No*
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*Unable to filter Reference Period, Employment, Age of Business, Product, Measure Type or Export and Import Activity.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Better contact details are available on the landing page and XLS spreadsheet
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by VTula2000** [comment]
Comments to BA's Review

- [ ] Unable to filter Reference Period, Employment, Age of Business, Product, Measure Type or Export and Import Activity

- Except Reference Period, other filter looks okay

- [ ] Better contact details are available on the landing page and XLS spreadsheet

- Scraper picks relevant information for meta data, This is noted in Scraper for any missing information further investigated

- [ ] Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?
- Data reviewed dimensions were as according to source data

- [ ] Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?
- Yes, PMDv4 Data need to be updated, Value `Total` is removed due to duplication in various tabs

**Comment by JasonHowell** [comment]
@VTula2000 according to the https://gss-cogs.github.io/family-trade/datasets/ the pipeline is "failing", so is this still ready to be signed off?

**Comment by mikeAdamss** [comment]
@JasonHowell - just doing some chasing/tidying up. This one is back to green (think it had a hiccup when you checked, working now).

**Comment by JasonHowell** [comment]
BA review but not quite ready to go.  A couple of issues:
- the "Age of Business" dimension is showing a URL, not the label
- We seem to have an old duplicate "International exports of services from subnational areas of the UK"

**Comment by JasonHowell** [comment]
Label has been tidied up and duplicate datasets removed.  Should be ready for final sign-off.

**Comment by JasonHowell** [comment]
Latest version on PMDv4.  BA's to review.

**Comment by JasonHowell** [comment]
BA's have reviewed and Good to go.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by Robsteranium** [comment]
The picker for the product dimension isn't showing.

It looks like the ons_abs_trades component is using the old style:

```turtle
<http://gss-data.org.uk/data/gss_data/trade/ons_abs/component/ons_abs_trades>
  <http://publishmydata.com/def/qb/codesUsed> <http://gss-data.org.uk/data/gss_data/trade/ons_abs/codes-used/ons_abs_trades> .
```

When it ought to be attached to the dimension via `qb:codeList`.

```turtle
<http://gss-data.org.uk/def/dimension/product> # or perhaps a subProperty thereof
  qb:codeList <http://gss-data.org.uk/data/gss_data/trade/ons_abs/codes-used/ons_abs_trades> .
```

Moreover, the dataset description promises a product breakdown by "SIC07" but we only have three values here: "Goods", "Services" or "Goods and Services". Perhaps this is a description of the ABS itself and not the "Exports and Importers" table provided in this cube? Alternatively, if there _is_ a SIC breakdown available for this table, perhaps we should include it.

**Comment by Robsteranium** [comment]
There's an issue for ["sub-property-ing" all of the product dimensions here](#70).

**Comment by Shannon95** [comment]
- [ ] Add Cubes() to transform (DE)

**Comment by LPerryman** [comment]
Data published on PMD4
Only published Business counts as proportion splits can be derived

**Comment by Shannon95** [comment]
Data published on Staging 
[Annual Business Survey exporters and importers - Business count](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_abs%2Fannual-business-survey-exporters-and-importers-business-count-catalog-entry)
[Annual Business Survey exporters and importers - Business proportion](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_abs%2Fannual-business-survey-exporters-and-importers-business-proportion-catalog-entry)
