### ISSUE TITLE
HMRC-RTS-Small-area

### ISSUE THREAD

**Issue by RedWalters** [GSS-Cogs/family-trade#322]
Uplifting HMRC-RTS-Small-areas to CSVCubed.

Currently working on 'csvcubed' branch.

**Comment by RedWalters** [comment]
CSVCubed pipeline up and running, almost ready to publish but there is currently an issue with uploading existing codelists to PMD in this new method, issue [here](https://github.com/GSS-Cogs/csvcubed/issues/311)

**Comment by Shannon95** [comment]
closing as uplift is complete, published and issue above has been resolved.
