### ISSUE TITLE
ONS-BOP-individual-country-data

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/family-trade#33]

**Comment by JasonHowell** [comment]
BA QA Feedback - Tracey B

BA Quality Assurance High Level Checks 
Dataset: Individual country data (goods) on a monthly basis
Completed by: Tracey Burgess
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes*
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
No**
Does transformed info seem to match the original?


Contents Modified Date
2018-11-07T13:47:50.296Z, 2019-10-22T13:58:53.650Z 2019-10-30T11:42:26.344Z, 2019-10-31T11:02:00.728Z, 2019-11-01T13:36:46.593Z, 2019-11-04T09:49:41.458Z, 2019-11-06T22:44:02.981Z, 2019-11-07T08:15:02.949Z, 2020-02-17T16:17:06.957Z2020-03-09T14:47:44.649Z2020-03-10T17:54:33.293Z2020-03-10T19:47:30.395Z2020-03-14T15:51:30.598Z
PMD V3
Is the dataset listed  in PMD V3?
Yes***
Does the dataset open?
Yes both 
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
30/03/2020 & 27/03/2020
General
Is the dataset title meaningful?
On the landing page yes but not when opened!
Do the filters work & look sensible?
No****
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*The dataset is listed as ‘Individual country data (goods) on a monthly basis from January 1998 to May 2017’, however when the dataset is opened in PMD v4 staging it appears as ‘ONS BoP Individual Country Data’.  

This is not the latest version of dataset.

***There are 2 datasets on PMD v3 ‘Individual country data (goods) on a monthly basis’  and ‘ONS BoP Individual Country Data’ which are linked to this dataset in PMD v4 staging

**** unable to filter by Reference period, Measure type not filterable so should be removed from the dataset dimensions to filter.

Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Not a lot of Meta data displayed better contact details are available on the landing page and XLS spreadsheet
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Not sure why Measure Type and unit of measure are both required?
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by JasonHowell** [comment]
@RedWalters   Why has this been closed?  Thanks Jason

**Comment by JasonHowell** [comment]
BA's have confirmed it is good to go in it's current state.

**Comment by Shannon95** [comment]
GitHub
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS_BoP_individual_countries
Jenkins
https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/

**Comment by osamede20** [comment]
Dataset transform was previously written in pandas and not outputting required files correctly.
Transform scraper re-written with databaker and outputting required csv, json and trig files correctly.

**Comment by JasonHowell** [comment]
Closing as looks fine on the Beta site

https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-bop-individual-countries-catalog-entry

Closing issue.
