### ISSUE TITLE
CDID codes including legacy and re-used codes

### ISSUE THREAD

**Issue by Grace-W** [GSS-Cogs/family-trade#59]
To investigate legacy and reused CDID codes for duplication. Pink Book and Quarterly National accounts use these codes.
Martyn is awaiting further information.
To use attribute for the time being.

Quarterly National Accounts
https://github.com/GSS-Cogs/family-trade/issues/13

Pink Book
https://github.com/GSS-Cogs/family-trade/issues/34

ONS_BoP
https://github.com/GSS-Cogs/family-trade/issues/1

ONS Trade in Goods 
https://github.com/GSS-Cogs/family-trade/issues/15

**Comment by Grace-W** [comment]
Exploration needed on the CDID codes as we have a codelist under Trade for the Pink Book. 
The initial decision made to keep the CDID as an attribute may be causing potential conflicts. 

ONS Trade in Goods had missing CDIDs
Pink book has empty values under some CDIDs which have been removed
CDID codes used in ONS BoP.

**Comment by MartynBSpooner** [comment]
Check that for the datasets listed that the CDID is extracted as an attribute.

**Comment by JasonHowell** [comment]
CDID is still an ongoing design topic and therefore this should be closed and used in supporting that conversation. 

A work around has been implemented until a design decision has been made. 

Closing issue.
