### ISSUE TITLE
ONS-UK-Total-trade

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#6]

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC-RTS-Small-area/82/)

Blocks #16

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_Trade/58/)

Blocks #8

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/34/)

Blocks #12

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/35/)

Blocks #12

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/36/)

Blocks #12

**Comment by ajtucker** [comment]
Build was fixed!

**Comment by Shannon95** [comment]
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context?
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by JasonHowell** [comment]
BA QA Feedback - Tracey B

BA Quality Assurance High Level Checks 
Dataset:  UK total trade: all countries, non-seasonally adjusted
Completed by: Tracey Burgess
Date: 06/04/2020
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes
Does transformed info seem to match the original?
Yes
Contents Modified Date
10/03/2020
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
26/03/2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
No*
Does the structure look sensible?
Yes

Overview
General comments on the dataset

*Unable to apply filters to Reference Period & Product
*Measure Type should not be included in the list of filterable dimensions and is this required as well as Unit of measure and GBP Total?

Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

See above re Measure type, unit of measure and GBP total

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

**Comment by Shannon95** [comment]
**BA/DE Review Summary of aspects to consider / fix** 

**Comments on what a user can see via PMDv4:** 
- Some of the filters are either not available for certain dimensions or not working as expected. (Unable to apply filters to Reference Period & Product)
- BA comment: Measure Type should not be included in the list of filterable dimensions and is this required as well as Unit of measure and GBP Total?
- Currently unable to download as CSV format
- Column which represents the same dimension is named different from PMDv3 (‘ONS Partner Geography’ ) and PMDv4 ( ‘Trade Partner Geography’) 


**Technical comments / aspects that can be fixed via transformation code or reference data.** 
- [ ] Marker not defined in transformation 
_This has now been fixed._ 

- [ ] Serbia country code in the dataset is RS however in the current shared codelsit is XS. Label has been added to this card to indicate it needs a specific dimension/codelist, has been hard coded to be XS for now within the transformation

- [ ] Conversation needed regarding title ‘ONS Partner Geography’ / ‘Trade Partner Geography’ if the decision is made to create a specific dimension/codelist for this column.

**Comment by Shannon95** [comment]
Update on issues and what is remaining:
- Country code issue regarding the use of different codes for Serbia fixed and now matching what is used in the original source data (RS). 
- Product filter issues on the PMDv4 side is fixed and now shows the user a more specific dimension name, in this case 'ONS ABS Trades' http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-total-trade-catalog-entry&=&order-by-component=http%253A%252F%252Fgss-data.org.uk%252Fdef%252Fdimension%252Fons-abs-trades&order-direction=ASC

- [ ] One remaining filter issues on the PMDv4 side is still present but being worked on. Issue has been flagged with swirl  and is regarding the Reference Period Filter errors. https://github.com/Swirrl/ons-data-export/issues

**Comment by JasonHowell** [comment]
BA's have confirmed it is good to go in its current state.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by Shannon95** [comment]
Available as a draft in PMD4 to review. Name : GSS_data/Trade/ONS-UK-Total-trade

**Comment by LPerryman** [comment]
PMD4 is throwing a wobbly with the draft dataset, won't display, think it might be something to do with the dataset_path. in the turtle output it is 
uk-total-trade-all-countries-non-seasonally-adjusted
but in the trig file it is:
ons-uk-total-trade
I might be wrong!

Can you also pathify the country code please, I forgot to mention in the spec?

**Comment by Shannon95** [comment]
Avilable on PMD4: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-total-trade-catalog-entry
Spec: https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-UK-Total-trade/spec.md

**Comment by Tracey-B** [comment]
@Shannon95  Subject to the usual caveats I am content for this to be published.

**Comment by JasonHowell** [comment]
This has been published and can be closed.
