### ISSUE TITLE
Add Alcohol Duty into Trade family.

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#66]
This covers the movement of Alcohol Duty into Trade:

- [x] update Airtable;
- [x] merge the Git repos and sync with Airtable;
- [x] fix any issues in the transformation #67;
- [x] check that dataset is included in [Trade dashboard](https://gss-cogs.github.io/family-trade/datasets/).

**Comment by JasonHowell** [comment]
@shannon95 I noticed Alex has created #67,  I think this is a duplicate of this one.   #67 is the one Alex is picking up on the Trade Dataset family dashboard, so might have to re-point to this one.

**Comment by Shannon95** [comment]
@JasonHowell thanks! I have assigned myself to the new card and moved to 'To fix' as I am still currently working on it.

**Comment by ajtucker** [comment]
I've updated the initial comment with a checklist and checked-off the bits that are done on this ticket. For "fix issues in transform", I've linked to the dataset issue #67 so that once that is closed, it should be automatically checked-off.

**Comment by JasonHowell** [comment]
@shannon95.  Can I close this one-off as a duplicate of #67?

**Comment by Shannon95** [comment]
@JasonHowell Yes can be closed as duplicate, thanks

**Comment by JasonHowell** [comment]
Closing as a duplicate of #67  .
