### ISSUE TITLE
HMRC-alcohol-bulletin

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#67]

**Comment by Shannon95** [comment]
QA LIST : Alcohol Bulletin 

This dataset has been updated and the transformation redone as the structure of the spreadsheet and landing page had changed.
The name reflected on PMDv3 and PMDv4 will now change from Alcohol Duty to Alcohol Bulletin. Dataset therefore needs updated on PMDv4. 

- [ ] Does the dataset show up or is there an error?
Yes. updated version present on PMDv3:  http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-alcohol-bulletin
PMDv4 needs updated. 
Old version called ‘Alcohol Duty’ present on PMDv3 and PMDv4. 

- [ ] Is it in the list of datasets from the main page?
Yes. 
- [ ] Is there descriptive metadata on the search page?
No. 
- [ ] Does transformed info match the original?
Yes. 
- [ ] Does the tidydata download show all the data?
No. PMDv3 only downloads one line at a time. 
- [ ] Note differences in column/row headers
N/A
- [ ] Are there multiple cubes? List titles of cubes
No. One cube:  Alcohol Bulletin 
- [ ] What needs differentiating? Totals
N/A
- [ ] Are there titles that need harmonising? World/Worldwide
No. 
- [ ] Does the structure look sensible?
Yes. 
- [ ] Does the hierarchy work?
Yes. 
- [ ] What needs further investigation or context?
Red screen server error appears after selecting any of the filters on PMDv3. 
- [ ] Any duplications?
No. 
- [ ] List any detailed metadata/methodology to add retrospectively
N/A
- [ ] Short metadata added
N/A

Comments:
Issues remaining seemed to be with PMDv3, although as the latest version is not yet available on PMDv4 the issues might be resolved once updated.

**Comment by JasonHowell** [comment]
Alcohol bulletin has been de-prioritised but will need to be picked up and progressed at a later date.

**Comment by LPerryman** [comment]
Have redone the spec as the format has changed. 
Scraper description still needs defining to account for all the information in the sheets. I will do this soon and add to spec.
Codelists also need to be created

**Comment by LPerryman** [comment]
Published to PMD4. Some Periods are still showing as URIs, cannot run ref_period pipeline at the moment, have asked for it to be looked at.

**Comment by LPerryman** [comment]
issue with periods now appears to be fixed

**Comment by JasonHowell** [comment]
This has all been completed.  There is a issue with the pipeline which will be investigated under #190. 

Closing issue.
