### ISSUE TITLE
Dimension labels

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#68]
Due to the way we've had to coin URIs for dimensions -- the dimension's label is used -- there are a number of dimensions where the label is not what the end user would expect.

A workaround for the time-being is to move the dimension definition from `reference/components.csv` to `reference/components.trig`. This also has the benefit of letting us properly synchronise the database as we can put the definitions into their own, separate graph.

Dimensions that need better labels:

- [ ] BOP Services
- [ ] SITC Section
- [ ] Trade Partner Geography -> Partner Geography
- [ ] Trade Reporter Geography -> Reporter Geography
- [ ] SITC 4
- [ ] ONS FDI Area
- [ ] FDI Component
- [ ] FDI Industry
- [ ] HMRC Industry
- [ ] NUTS Geography
- [ ] ONS Functional Category
- [ ] ONS Trade Areas ITIS
- [ ] ITIS Service
- [ ] ITIS Industry
- [ ] SIC Industry
- [ ] ONS Partner Geography
- [ ] 1Y deflator GR, etc. (measures)
- [ ] Service Origin Geography
- [ ] Service Destination Geography
- [ ] MRETS Product
- [ ] HMRC Trade Statistic Type
- [ ] HMRC Reporter Region
- [ ] HMRC Partner Geography
- [ ] CORD SITC
- [ ] CORD Geography

**Comment by Robsteranium** [comment]
Who do we mean by "end user" and what would they expect?

Is the idea that a child dimension would adopt the label from it's parent? Perhaps it'd be better to display the parent dimension instead?
