### ISSUE TITLE
Fix Product Super dimension

### ISSUE THREAD

**Issue by VTula2000** [GSS-Cogs/family-trade#70]
To generate all the datasets use a specific dimension for their “product” dimension, then each of these dimensions is made a “sub property” of this “product” dimension.

CProduct dimension in PMD3 is based on various specific dimensions of data sets, that includes

Combined Nomenclature
ITIS Service
Pink Book Services
HMRC Industry
ONS ABS Trade
ONS Functional Category
Need to generate to specific dimension for each data sets  with its code list to make `Product`  as main dimension

**Comment by VTula2000** [comment]
![image](https://user-images.githubusercontent.com/36479963/81282624-53276f00-9053-11ea-81d7-0da99d8ea992.png)

**Comment by VTula2000** [comment]
- [ ] In ONS UK Trade in Services generate  `Pink Book services` Dimension and code list title specific to  data set

- [ ] In ONS UK Total Trade generate `ONS ABS Trade` Dimension and code list title specific to  data set

- [ ] New specific Code list required for CPA 2008 related to product dimension

- [ ] In ONS International exports of services from sub national areas of the UK generate data specific dimension

**Comment by VTula2000** [comment]
Updated as according to below table with relevant data specific dimension and code list
![image](https://user-images.githubusercontent.com/36479963/81801799-e0177000-950c-11ea-867c-2b4bae31add8.png)

**Comment by rossbowen** [comment]
Done some review on these and don't think they coalesce into a single dimension. Some improvements been made to explicitly use SIC and SITC codes where possible, will close and track anything outstanding per dataset.
