### ISSUE TITLE
BOP Vademecum to SKOS needs a hierarchy / breakdown.

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#72]
Check if we can already get this information in a machine readable format/file. Otherwise see whether we can pull it out from the comments.

- [ ] 1 day investigation

**Comment by rossbowen** [comment]
Related. https://github.com/GSS-Cogs/ref_sdmx/issues/1.

**Comment by LPerryman** [comment]
Codelists have been extracted using the following dodgy script:
https://github.com/GSS-Cogs/ref_common/blob/pmd4/reference/bop-sdmx-codelists/sdmx-bop-vademacum.ipynb

Source:
https://registry.sdmx.org/ws/public/sdmxapi/rest/datastructure/IMF/BOP/1.14/?detail=full&references=descendants&version=2.1

And hierarchy has been produced using the following nightmare script:
https://github.com/GSS-Cogs/ref_common/blob/pmd4/reference/bop-sdmx-codelists/code-for_bop-hierarchies.ipynb

The description (if there is one) is split by various means to get the hierarchy, i have ignored a few of the more complicated ones (+ plus - that from then until that etc.), In 3 cases the label has been used.
In the cases where their is "from" or "until" then the year involved is compared against the current year, so if its from 2007 then it is included, if it is until 2013 then it is not included.
At the end of one of the codes it has A35E9, this does not reference anything so i have ignored it, A35 and E9 are not codes. A7E9 is a code so maybe they have missed one out
(Persian Gulf Economies (CDIS), S35E, 718,S35E = BH + IQ + IR + KW + OM + QA + SA + AE + A35E9) 
Could not stop rdflib using PREFIX's so have just replaced all instances of prefixes at the end using string replace function.

This is the resulting turtle file with lots of multiple Narrower and Broader instanced for some codes. Have replicated output from jenkins, metadata is in their somewhere just not at the top.
https://github.com/GSS-Cogs/ref_common/blob/pmd4/reference/bop-sdmx-codelists/cl-area.ttl
