### ISSUE TITLE
New trade datasets

### ISSUE THREAD

**Issue by Robsteranium** [GSS-Cogs/family-trade#74]
DIT have suggested some more datasets to add to this family.

Some we have already - I've included them here for completeness and in case we want to rename them for recognisability.

#### ONS Foreign direct investment (FDI) totals for inward and outward flows, positions and earnings
Already have this [here](https://trade.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-fdi-catalog-entry)

#### ONS trade in goods by business characteristics
Already have this [here](https://trade.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc_trade-catalog-entry)

#### ONS trade in services by business characteristics
Don't have this.

[Data](https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/datasets/uktradeinservicesbybusinesscharacteristics)

#### ONS Modes of supply
Don't have this.

[Data](https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/articles/modesofsupplyukexperimentalestimates/2018/relateddata)

[Docs](https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/articles/modesofsupplyukexperimentalestimates/2018) (needed to define the modes!)

#### ONS ITIS

[Already have this](https://trade.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry)

#### ONS Regional GDP

Don't have this.

[Data](https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/quarterlycountryandregionalgdp)

Looks like you can get lower splits too nowadays: [by city region](https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/regionalgrossdomesticproductcityregions) and [by enterprise region](https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/regionalgrossdomesticproductenterpriseregions).

#### ONS Trade in services by industry, country and service type

Don't have this.

[Data](https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/articles/uktradeinservicesbyindustrycountryandservicetype/2016to2018/relateddata)

NB: There are two tables there, it looks like we could pop them in a single cube with the addition of a flow dimension.

#### HMRC RTS business counts
Don't have this.

[Data](https://www.gov.uk/government/statistical-data-sets/regional-trade-statistics-interactive-analysis-second-quarter-2020)

Ignore the visible macro-powered sheets, and unhide the rest to reveal the observations and reference data.

#### ONS trade data excluding precious metals

Don't have this.

[Search](https://www.ons.gov.uk/search?q=ONS+trade+data+excluding+precious+metals)

Note the dataset ID is MRET and there are multiple time series IDs.

It should be inside MRETS which we have [here](https://trade.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets-catalog-entry&filters-drawer=open) but we're missing "TlessPM".

#### ONS UK Economic Accounts: balance of payments - current account

Don't have this. Indeed this isn't the only BoP table we're missing.

[Data](https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/datasets/balanceofpaymentsstatisticalbulletintables)

#### ONS International trade in services by subnational areas of the UK

[Only seem to have exports](https://trade.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-reuk-service-catalog-entry)

[Data](https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/datasets/internationaltradeinservicesbysubnationalareasoftheuk)

#### DCMS Sectors Economic estimates: Trade  

Don't have this.

[Data](https://www.gov.uk/government/statistics/dcms-sectors-economic-estimates-2018-trade-in-services)

**Comment by Shannon95** [comment]
**ONS Foreign direct investment (FDI) totals for inward and outward flows, positions and earnings** 
Updated version on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-foreign-direct-investment-involving-uk-companies-catalog-entry&apply-filters=false) 
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-foreign-direct-investment-involving-uk-companies-catalog-entry)

**ONS trade in goods by business characteristics**
Updated version on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-trade-in-goods-by-business-characteristics-catalog-entry)
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-trade-in-goods-by-business-characteristics-catalog-entry)

**ONS Modes of supply** 
Note consists of the Imports and Exports data joined together. 
Available on Staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supply-catalog-entry&apply-filters=false)
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supply-catalog-entry)

**ONS ITIS**
Available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry&apply-filters=false) 
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry)

**ONS Regional GDP**
Available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-quarterly-country-and-regional-gdp-catalog-entry&apply-filters=false) 
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-quarterly-country-and-regional-gdp-catalog-entry)

**ONS Trade in services by industry, country and service type**
Note consists of the Imports and Exports data joined together. 
Available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-industry-country-and-service-type-exports-catalog-entry)
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-industry-country-and-service-type-exports-catalog-entry) 

**HMRC RTS business counts**
Available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-interactive-analysis-catalog-entry) 
Not on beta yet.

**ONS trade data excluding precious metals**
MRETS data available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets-catalog-entry)  
note only published CVM data for now. 
TlessPM is within the other output for CP which is being worked on. 
neither available on beta yet. 

**ONS UK Economic Accounts: balance of payments - current account**
note split out into 6 on staging ; [Primary Income](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-primary-income-catalog-entry), [Secondary Income ](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-secondary-income-catalog-entry), [Summary](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-summary-of-balance-of-payments-catalog-entry), [Goods & Services](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-trade-in-goods-and-services-catalog-entry),  [Transactions with non-eu countries ](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-transactions-with-non-eu-countries-catalog-entry), [Transactions with EU and EMU ](https://staging.gss-data.org.uk/catalog-entry/find-submodule?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-economic-accounts-balance-of-payments-current-account%2Fuk-economic-accounts-balance-of-payments-current-account-transactions-with-the-eu-and-emu-catalog-entry)
Not on beta yet. 

**ONS International trade in services by subnational areas of the UK**
The updated version including Exports and Imports available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-by-subnational-areas-of-the-uk-catalog-entry)
Available on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-by-subnational-areas-of-the-uk-catalog-entry)

**DCMS Sectors Economic estimates: Trade**
Available on staging [here](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fdcms-sectors-economic-estimates-year-trade-in-services-catalog-entry)
Avilable on beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fdcms-sectors-economic-estimates-year-trade-in-services-catalog-entry)
