### ISSUE TITLE
Miscelleanous naming suggestions

### ISSUE THREAD

**Issue by Robsteranium** [GSS-Cogs/family-trade#75]
A few suggestions occur to me looking at the existing datasets catalogue.

#### BoP (*) datasets
- would benefit from individual descriptions (can't see the difference from the catalogue)

#### 03 Trade in services, The Pink Book
- Catalog looks odd with the first entry start with the number 3 - especially since the other chapters aren't loaded so no-one will every find them.
- Ordering of "<chapter>, <publication>" is reverse v.v. BoP.
- Suggest: "The Pink Book: Trade in Services"

#### Annual Business Survey exporters and importers
- tweak for consistency: "Annual Business Survey: Exporters and Importers"

#### Alcohol Bulletin
- looking at [the publication itself](https://www.gov.uk/government/statistics/alcohol-bulletin), we should call this "UK Alcohol Duty Statistics"
- the data is really quite confusing. Perhaps the model could be tweaked to put more stuff into related resources. I've not dug into this properly but the presentational spreadsheet makes use of nested headers which might suggest some changes to nest dimensions/ codes.

#### Quarterly National Accounts, GDP – data tables: Expenditure indicators
- can we simplify to: "Quarterly National Accounts: Expenditure indicators"? This would be more consistent with the "<publication>: <cube>" pattern.
- each dataset/ cube ought to have its own description

#### (HMRC) UK trade in goods by business characteristics
- "HMRC Trade Statistic Type" is a mysterious name for a dimension 
- How can "Business count by industry group" be measured in GBP Million? Isn't this the number of businesses?

**Comment by JasonHowell** [comment]
Need to work through the feedback Robin has given and decide whether it can be actioned or not.

**Comment by Shannon95** [comment]
These naming suggestions have been taken into consideration. We asked for feedback from the publisher when doing QA reviews with them in which some requested name changes. Closing as I believe these have been done/reviewed.
