### ISSUE TITLE
ONS-UK-trade-in-services-by-industry-country-and-service-type-exports

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#80]

**Comment by LPerryman** [comment]
Can be joined with 
https://github.com/GSS-Cogs/family-trade/issues/82

**Comment by Shannon95** [comment]
Note joined with ONS-UK-trade-in-services-by-industry-country-and-service-type-imports
#82 
Imports transformation is run inside the Exports main and joined together there.

The transformation process of Imports is still detailed within its own main for reference.

This pipeline (ONS-UK-trade-in-services-by-industry-country-and-service-type-exports) will represent both Exports and Imports, the naming therefore might need to be altered.

**Comment by Tracey-B** [comment]
BA comments:

There are a number of URLs in the industry field.
Unit of Measure - GBP should be GBP Million.
The usual caveats  also apply. 
This dataset has been joined with Github issue #82 comments have been added to this record too.

**Comment by Shannon95** [comment]
@Tracey-B updates have been made in line with your comments above. 

- [ ] No URLs should be present within the industry field now. (I believe it was only for 3 options; No industry - N, Total Unknown industry - U)

- [ ] Unit of Measure has been changed to 'GBP Million' 

Could you please check from a BA perspective you are happy with the fixes in place for above comments and content that this dataset can be published? 

PMD4: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-services-by-industry-country-and-service-type-exports%2Fpcn-catalog-entry
Spec: https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/spec.md

Thank you.

**Comment by Tracey-B** [comment]
@Shannon95 Happy that the above fixes have been actioned and subject the usual caveats this can be published.  Thanks
