### ISSUE TITLE
ONS-Regional-gross-domestic-product-enterprise-regions

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#81]

**Comment by CharlesRendle** [comment]
I haven't removed the super script in year value for 2018 as I'll wait to see the guidance on the spec.
Not quite sure what to do with blank values associated with the year 1998
Have taken the unit on each tab from the cell X1 but tabs 8 and 9 have a rather dubious value (2016=100).

**Comment by LPerryman** [comment]
Can be joined with transfrom https://github.com/GSS-Cogs/family-trade/issues/79

**Comment by LPerryman** [comment]
LEP = Local Enterprise Partnerships

**Comment by Shannon95** [comment]
Joined with #79. Please see comments on #79 issue card
