### ISSUE TITLE
ONS-UK-trade-in-services-by-industry-country-and-service-type-imports

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#82]

**Comment by LPerryman** [comment]
Can be joined with
https://github.com/GSS-Cogs/family-trade/issues/80

**Comment by Shannon95** [comment]
Note joined with ONS-UK-trade-in-services-by-industry-country-and-service-type-exports
#80 
Imports transformation is run inside the Exports main and joined together there.

The transformation process of Imports is still detailed within its own main for reference.

**Comment by Tracey-B** [comment]
BA comments:

There are a number of URLs in the industry field.
Unit of Measure - GBP should be GBP Million.
The usual caveats  also apply. 
This dataset has been joined with Github issue #80 comments have been added to this record too.

**Comment by rossbowen** [comment]
Merged with https://github.com/GSS-Cogs/family-trade/issues/80.
