### ISSUE TITLE
ONS-Exports-of-services-by-country-by-modes-of-supply

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#83]

**Comment by LPerryman** [comment]
To be joined with ONS-Exports-of-services-by-country-by-modes-of-supply
https://github.com/GSS-Cogs/family-trade/issues/88

**Comment by Shannon95** [comment]
Note  joined with ONS-Imports-of-services-by-country-by-modes-of-supply
https://github.com/GSS-Cogs/family-trade/issues/88
Imports transformation is run inside the Exports main and joined together there. 

The transformation process of Imports is still detailed within its own main for reference. 

Stage one, two and join done, for now, the pipeline needs to be added to Jenkins in order to run.

**Comment by Tracey-B** [comment]
BA Comments:

There are a number of URLs in the direction column.
Unit of Measure should be GBP Million.
The usual caveats apply.
This dataset has been combined with Exports of services by country by modes of supply and I will apply the comments to Github issue #88 too.

**Comment by Shannon95** [comment]
New release of source data. The publisher has changed tab names / added another tab, therefore, transformation needed to be updated. 
Updates have been made and available on PMD4 here: 

https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supplygss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supply-catalog-entry

Though there are a few issues in regards to the reference side: 

URL's appearing in two columns: 
- Marker: The new release is representing 2019 estimates so the _Marker_ column has been populated with '_estimated_'
- Mode: The new release has another value for dimension _Mode_: total-modes-1-2-and-4

As this data is joined with #88 the same applies.

**Comment by Shannon95** [comment]
@Tracey-B updates have been made in line with your comments above. 

- [x] No URLs should be present within the Direction field now. 
- [x] Unit of Measure has been changed to 'GBP Million' 

Note there had been a new release of this data and the transformation had to be updated to reflect that the new data represents estimated values of 2019. I had a few issues with URL's also as you can see from my comments above, these have also been resolved. 

Could you please check from a BA perspective you are happy with the fixes in place for above comments and content that this dataset can be published? 

PMD4: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supplygss_data%2Ftrade%2Fons-exports-of-services-by-country-by-modes-of-supply-catalog-entry

Spec: https://github.com/GSS-Cogs/family-trade/blob/master/datasets/ONS-Exports-of-services-by-country-by-modes-of-supply/spec.md

Thank you :)

**Comment by Tracey-B** [comment]
URLs in the direction column appear to have been resolved and the Unit of Measure has been updated to GBP MIllion, subject to the usual caveats this data set can be published.

The new release has 2 additional values for dimension Mode: total-modes-1-2-and-4 which is reflected as modes 1 2 4 and mode 3

This dataset has been combined with Exports of services by country by modes of supply and I will apply the comments to Github issue #88 too although mode 3 is aonly applicable to Exports.

**Comment by Shannon95** [comment]
After a conversation with @Tracey-B and updating spec with changes due to the new release, Happy that the above fixes have been actioned and subject the usual caveats this can be published.

(notes will be copied over to #88 )
