### ISSUE TITLE
HMRC-Regional-trade-statistics-interactive-analysis

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#87]

**Comment by LPerryman** [comment]
Have finished stage 2 spec but it will need a bit more work on the metadata once we know how many datasets are coming out the other end. Hopefully it can be one multi-measure cube.

**Comment by LPerryman** [comment]
Links in spreadsheet do not work:
https://www.uktradeinfo.com/Statistics/RTS/Pages/default.aspx	
https://www.uktradeinfo.com/Statistics/BuildYourOwnTables/Pages/Home.aspx

**Comment by LPerryman** [comment]
Have created local codelists as their are some extra bits in the Region and Country columns (Stores and Provisions, Unallocated known). Have to start deciding how we are going to take care of this as the Country codelist would probably match up with the ONS Country codes and the Region codelist could have ONS Geography codes assigned

**Comment by ajtucker** [comment]
I re-created the codelist's `-metadata.json` files using `codelist-manager` and then manually changed the URIs to prepend `hmrc-` to the IDs as there's an issue with `codelist-manager` (see GSS-Cogs/gss-utils#160).

The drafter tests now all pass, though there are still some issues with URIs by the looks.

**Comment by ajtucker** [comment]
Looking at the column mapping in `info.json` and the output in PMD:

- [ ] "Period": can we just use the `"dimension"` key and point to `http://purl.org/linked-data/sdmx/2009/dimension#refPeriod` directly?
- [ ] "Flow": can we just use `"dimension"` key and use the family level "flow" dimension directly? Also, the `"value"` looks to have the wrong URI template.
- [ ] "Measure Type": it looks as though the measure types need defining somewhere as they're showing up as URIs in PMD.
- [ ] "Unit": as above, it looks as though the unit attributes used need defining somewhere.

**Comment by mikeAdamss** [comment]
fixed, moving it over (timed out on the sparql query stage so restarted it).

**Comment by rossbowen** [comment]
Reference periods currently have lowercase q's causing the reference period pipeline to throw some errors.

**Comment by mikeAdamss** [comment]
this popped up on my alerts, main.py has two `COLUMNS_TO_NOT_PATHIFY` constants in it. If you add "Period" to the list for each (whoever picks this up) I suspect that'll fix it.

**Comment by Shannon95** [comment]
Avilable on PMD and ready for review here https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-interactive-analysis-catalog-entry&filters-drawer=closed

**Comment by JasonHowell** [comment]
This has been published to Beta and can be closed.  #229 will be followed up seperately.
