### ISSUE TITLE
Publisher descriptions missing from trade.gss-data.org.uk

### ISSUE THREAD

**Issue by Robsteranium** [GSS-Cogs/family-trade#94]
The datasets on trade.gss-data.org.uk specify a couple of publishers:

https://www.gov.uk/government/organisations/office-for-national-statistics
https://www.gov.uk/government/organisations/hm-revenue-customs

We've not loaded descriptions for these. We ought to add labels so that these will be searchable on the catalogue and displayed on the dataset "about" tab.

We might also like to [load acronyms at the same time so that they might be picked up in search at some point](https://github.com/Swirrl/cogs-issues/issues/153).

**Comment by JasonHowell** [comment]
Trade.gss-data.org.uk all Trade datasets have been moved over to the Beta site and therefore no further actions will be taken on Trade.gss-data.org.uk site. 

Closing issue.
